server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
#  cloud:
#    nacos:
#      server-addr: 47.98.185.242:8848
#    sentinel:
#      enabled: true
#      transport:
#        dashboard: 47.98.185.242:8849
#        clientIp: localhost
