server:
  port: 8082

spring:
  application:
    name: ADMIN-SERVICE
  cloud:
    nacos:
      server-addr: 47.98.185.242:8848
    sentinel:
      enabled: true
      transport:
        dashboard: 47.98.185.242:8849
        clientIp: localhost